version: '3'
services:
    cypress_testing:
        image: cypress_compose
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - dockerReports:/app/cypress/results/

volumes:
 dockerReports:

