name: Cypress E2E Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: Cypress E2E Tests
    steps:
      - run: echo "Hello from this API, ${APIURL}"
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
         browser: chrome
